// Generated by CoffeeScript 1.8.0
(function() {
  var os, ua;

  ua = new UAParser;

  os = ua.getOS().name;

  if (os === 'iOS' || os === 'Android') {
    if (os === 'Android') {
      $('#apple-store').hide();
    } else if (os === 'iOS') {
      $('#play-store').hide();
    }
    $('.linkTextingWidget').hide();
  }

}).call(this);

var expandLink = document.getElementById('expand-link');
var examples = document.getElementById('example-list');
var events = ['click', 'touchend'];

if(examples){
for(event of events){

  expandLink.addEventListener(event, function(){
    examples.classList.toggle('expanded');
    if (examples.classList == 'expanded') {;
      expandLink.innerHTML = "Collapse examples";
    }else{
      expandLink.innerHTML = "Show more examples";
    }
  }, false);

}

}
// window.addEventListener('touchend', function(){
//   console.log('touched')
// },false)
// Smooth scrolling for same page links
$(document).ready(function() {
   $('a[href*=#]').bind('click', function(e) {
  e.preventDefault(); //prevent the "normal" behaviour which would be a "hard" jump
       
  var target = $(this).attr("href"); //Get the target
      
  // perform animated scrolling by getting top-position of target-element and set it as scroll target
  $('html, body').stop().animate({ scrollTop: $(target).offset().top}, 500, function() {
       location.hash = target;  //attach the hash (#jumptarget) to the pageurl
  });
      
  return false;
   });
});


var events = ['click', 'touchend'];
var $tabContent = $('.tab-item');
var locked = false;

$(document).ready(function(){

  var $legalMenu = $('.legal-menu');
  var $leftOffset = $legalMenu.offset().left
  
  $(window).on('scroll', function(e){
    var currentScroll = this.scrollY;

    if(currentScroll > 88 && !locked){

      locked = true;
      var $shim = $($legalMenu).clone()
        .attr('id','Shim')
        .prependTo($($legalMenu).parent()
      );

      $($legalMenu)
        .css('left', $leftOffset)
        .addClass('sticky');      
    }else if(currentScroll < 88){
      $($legalMenu).removeClass('sticky')
      $('#Shim').remove();
      locked = false;
    }
  })
})  



//
var alternateImage = (function(){

  var _altImage = function(name) {
    $('#' + name).on('mouseenter', function(e){
      return $(e.target).attr('src', "/images/" + name + "_alt.gif");
    }).on('mouseleave', function(e){
      return $(e.target).attr('src', "/images/" + name + ".jpg");
    });
  };

  return {
    gif: _altImage
  }

})();



names = ['joint', 'sidney', 'loren'];

for(name in names){
  alternateImage.gif(names[name]);

}