---
#product demo screen shots
- title: "Parlay for money, bragging rights, or charity"
  image: screenshot_aa

- title: See what friends are up to
  image: screenshot_bb

- title: React, comment, and share
  image: screenshot_cc

- title: Build a profile
  image: screenshot_dd

- title: Donate to charity
  image: screenshot_ee

# - title: Parlay for pics
#   image: screenshot_f  