---
#product demo screen shots
- title: "Parlay for pics, charity or money"
  image: screenshot_a

- title: Build a profile 
  image: screenshot_b

- title: Persue your friend feed
  image: screenshot_c

- title: Comment and emote
  image: screenshot_d

- title: Parlay for charity
  image: screenshot_e

- title: Parlay for pics
  image: screenshot_f  