---
#product demo screen shots
- title: Build a profile
  image: screenshot_a

- title: Persue your friends
  image: screenshot_b

- title: "Comment, emote, share"
  image: screenshot_c

- title: "Parlay for pics, charity or money"
  image: screenshot_d