---
#product demo screen shots
- title: "Parlay for money, bragging rights, or charity"
  image: screenshot_a

- title: See what friends are up to
  image: screenshot_b

- title: React, comment, and share
  image: screenshot_c

- title: Build a profile
  image: screenshot_d

- title: Donate to charity
  image: screenshot_e

# - title: Parlay for pics
#   image: screenshot_f  