// Generated by CoffeeScript 1.8.0
(function() {
  var os, ua;

  ua = new UAParser;

  os = ua.getOS().name;

  if (os === 'iOS' || os === 'Android') {
    if (os === 'Android') {
      $('#apple-store').hide();
    } else if (os === 'iOS') {
      $('#play-store').hide();
    }
    $('.linkTextingWidget').hide();
  }

}).call(this);
